version: "2"

services:
  equipment-ui:
    image: openlmis/dev-ui:${OL_DEV_UI_VERSION}
    ports:
      - "9000:9000"
      - "9876:9876"
    working_dir: /app
    volumes:
      - '.:/app'
    env_file: .env
    volumes_from:
      - auth-ui
      - referencedata-ui
      - ui-components
      - ui-layout
    depends_on:
      - auth-ui
      - referencedata-ui
      - ui-components
      - ui-layout
  auth-ui:
    image: openlmis/auth-ui:${OL_AUTH_UI_VERSION}
    volumes:
      - '/openlmis-auth-ui'
  referencedata-ui:
    image: openlmis/referencedata-ui:${OL_REFERENCEDATA_UI_VERSION}
    volumes:
      - '/openlmis-referencedata-ui'
  ui-components:
    image: openlmis/ui-components:${OL_UI_COMPONENTS_VERSION}
    volumes:
      - '/openlmis-ui-components'
  ui-layout:
    image: openlmis/ui-layout:${OL_UI_LAYOUT_VERSION}
    volumes:
      - '/openlmis-ui-layout'
  image:
    build: .
    image: openlmismz/equipment-ui
